# Documentation: https://github.com/sasstools/sass-lint/tree/master/docs/options
# All available rules: https://github.com/sasstools/sass-lint/tree/master/docs/rules
options:
  include: './app/**/*.scss'
  merge-default-rules: false
rules:
  attribute-quotes: 2
  bem-depth: 0
  border-zero:
    - 2
    - convention: none
  brace-style:
    - 2
    - style: 1tbs
  class-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  clean-import-paths:
    - 2
    - leading-underscore: false
      filename-extension: false
  declarations-before-nesting: 2
  empty-args: 0
  empty-line-between-blocks:
    - 2
    - include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  function-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  hex-length:
    - 2
    - style: long
  hex-notation:
    - 2
    - style: uppercase
  id-name-format: 0
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: true
  max-file-line-count:
    - 1
    - length: 300
  max-line-length:
    - 2
    - length: 100
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations: 0
  nesting-depth:
    - 1
    - max-depth: 3
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 2
  no-color-literals:
    - 1
    - allow-rgba: false
      allow-variable-identifies: false
      allow-map-identifiers: false
  no-combinators: 1
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  property-sort-order:
    - 2
    - order: alphabetical
  property-units: 0
  pseudo-element: 0
  quotes:
    - 2
    - style: single
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang: 0
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 0
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property:
    - 1
    -
      'properties':
      - 'margin'
      - 'padding'
  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit: 2
